### ISSUE TITLE
[1.18.2] Crashes with Powah! (Rearchitected)

### ISSUE THREAD

**Issue by Doctor-Duck** [shedaniel/slight-gui-modifications#78]
I am getting a crash from Slight GUI Modifications when using the Fabric port of Powah! I and another user reported this crash in [this ](https://github.com/Technici4n/Powah/issues/13)thread, and was told to report the issue here.

My crash log: https://crashy.net/alPixEzRytkbrXFsQXi9

**Comment by 0gp** [comment]
I can confirm this issue.
Hope it can be fixed soon.
Thank you.

**Comment by warior456** [comment]
[https://cdn.discordapp.com/attachments/922828438274986007/997413413468782612/message.txt](https://cdn.discordapp.com/attachments/922828438274986007/997413413468782612/message.txt)

**Comment by shedaniel** [comment]
Should be fixed in 2.2.1

**Comment by DougStoker** [comment]
[2022-10-27-3.log.gz](https://github.com/shedaniel/slight-gui-modifications/files/9881260/2022-10-27-3.log.gz)

still happening, thanks.
